name: update-readme

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

jobs:
  update_readme:
    name: Readme mods
    runs-on: ubuntu-latest
    needs:
      - build_image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Repo Readme/Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ inputs.repo_name }}
          readme-filepath: ./README.md
